---
# tasks file for manage-distracting-sites

# NOTE: We ignore this task and use symlinked vars/config file for simplicity
# We can stat and create file, or use touch
# For our use case touch works
# Refer - http://stackoverflow.com/questions/28347717/how-to-create-an-empty-file-with-ansible
# - name: Ensure file with distracting sites list exists
#   file:
#     path="~/.distracting_sites_ansible_focus_love.yml"
#     state=touch

- name: Block supplied site
  lineinfile:
    dest=/etc/hosts
    state=present
    regexp="{{ user_input_distracting_site }}"
    line="127.0.0.1        {{ user_input_distracting_site }} www.{{ user_input_distracting_site }}"
    insertafter=EOF
  when: user_action == "block" and user_input_distracting_site is defined

- name: Add supplied site to distracting sites list
  lineinfile:
    dest={{ playbook_dir }}/group_vars/all/config.yml
    state=present
    follow=yes
    regexp="{{ user_input_distracting_site }}"
    line="  - {{ user_input_distracting_site }}"
    insertafter=EOF
  when: user_action == "block" and user_input_distracting_site is defined

- name: Block each distracting site
  lineinfile:
    dest=/etc/hosts
    state=present
    regexp="{{ item }}"
    line="127.0.0.1        {{ item }} www.{{ item }}"
    insertafter=EOF
  when: user_action == "block" and user_input_distracting_site is not defined
  with_items: distracting_sites

- name: Unblock supplied site
  lineinfile:
    dest=/etc/hosts
    state=absent
    regexp="{{ user_input_distracting_site }}"
  when: user_action == "unblock" and user_input_distracting_site is defined

- name: Unblock each distracting site
  lineinfile:
    dest=/etc/hosts
    state=absent
    regexp="{{ item }}"
  when: user_action == "unblock" and user_input_distracting_site is not defined
  with_items: distracting_sites

- name: Clear the DNS cache
  shell: "dscacheutil -flushcache"

